version: '3.8'
services:
  app:
    image: laravel:latest
    ports:
      - 8000:8000
    volumes:
      - .:/var/www
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: order_management
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
